// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk2EAM377HdSp2qCwvgCS4g4qu6nIAPxU',
    appId: '1:640712128382:web:a6cfa04fc5d2939e6d652f',
    messagingSenderId: '640712128382',
    projectId: 'notesapp-cd2dd',
    authDomain: 'notesapp-cd2dd.firebaseapp.com',
    storageBucket: 'notesapp-cd2dd.appspot.com',
    measurementId: 'G-V5L01QSRKS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCmOUlivmKaFLtHD-5Pj7Ok9mqKA_WikA',
    appId: '1:640712128382:android:277b48a30915be8e6d652f',
    messagingSenderId: '640712128382',
    projectId: 'notesapp-cd2dd',
    storageBucket: 'notesapp-cd2dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC62BxIHtfNfhd0QcHZLTeTC2_oaLr56FQ',
    appId: '1:640712128382:ios:dccbeac98daf3aba6d652f',
    messagingSenderId: '640712128382',
    projectId: 'notesapp-cd2dd',
    storageBucket: 'notesapp-cd2dd.appspot.com',
    iosBundleId: 'com.example.adExam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC62BxIHtfNfhd0QcHZLTeTC2_oaLr56FQ',
    appId: '1:640712128382:ios:dccbeac98daf3aba6d652f',
    messagingSenderId: '640712128382',
    projectId: 'notesapp-cd2dd',
    storageBucket: 'notesapp-cd2dd.appspot.com',
    iosBundleId: 'com.example.adExam',
  );
}
